### ISSUE TITLE
Scale down images using img-fluid

### ISSUE THREAD

**Issue by Quintasan** [asi-wroclaw/asi.wroclaw.pl#17]
Some images are too big and cause horizontal scrolling. Please parse all blog posts in `source/blog` directory and add `img-fluid` to all images

Here's Markdown syntax for additional attributes https://forum.middlemanapp.com/t/automatically-add-class-to-img-tag-for-every-blog-post/1761/3

**Comment by jakdor** [comment]
Use sth like this:
`![](img.png){:class="col-sm-12 img-responsive"}`
